=== MXblade/BeihaiparkMap/xml/BHpark.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.w3school.com.cn" targetNamespace="http://www.w3school.com.cn" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="park">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="view_spot" maxOccurs="50">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="history" type="xs:string"/>
							<xs:element name="description" type="xs:string"/>
							<xs:element name="location">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="x" type="xs:integer"/>
										<xs:element name="y" type="xs:integer"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MXblade/BeihaiparkMap/xml/BHpark.xml
<?xml version="1.0" encoding="UTF-8"?>
<park xmlns="http://www.w3school.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3school.com.cn BHpark.xsd">
	<view_spot>
		<name>碧鲜亭</name>
		<history>明朝</history>
		<description>美丽</description>
		<location>
			<x>325</x>
			<y>65</y>
		</location>
	</view_spot>
	<view_spot>
		<name>北海静心斋</name>
		<history>明朝</history>
		<description>静心斋原名“镜清斋”，占地面积约八千七百平方米。是北海最精巧的一处园中之园。静心斋原为明代普通官房，清乾隆二十四年（公元1757年）在扩建“西天梵境”时修建了静心斋（当时称镜清斋）也称“乾隆小花园”。园内主要建筑有镜清斋、抱素书屋、韵琴斋、碧鲜亭、焙茶坞、罨画轩、沁泉廊、枕峦亭、石桥等。静心斋东枕山，西倚寺，南面沧波，园内亭、榭、廊、轩、石桥、水池、叠石、假山以及楼台，殿阁建筑形式既不失北方园林宏伟壮丽的气魄，又有江南园林小巧玲珑的情趣，是中国造园艺术的珍品</description>
		<location>
			<x>290</x>
			<y>70</y>
		</location>
	</view_spot>
	<view_spot>
		<name>大慈真如殿</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>250</x>
			<y>100</y>
		</location>
	</view_spot>
	<view_spot>
		<name>华藏界</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>261</x>
			<y>144</y>
		</location>
	</view_spot>
	<view_spot>
		<name>西天梵境</name>
		<history>明朝</history>
		<description>“西天梵境”又称大西天，东临静心斋，西与大圆境智宝殿相依，南与琼华岛贯成一线，是北海最负盛名的景区之一，原为明代西天禅林喇嘛庙，清代于 1759 年重修，并向西扩展，1980 年经重新修缮后对外开放。</description>
		<location>
			<x>250</x>
			<y>129</y>
		</location>
	</view_spot>
	<view_spot>
		<name>天王殿</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>246</x>
			<y>137</y>
		</location>
	</view_spot>
	<view_spot>
		<name>九龙壁</name>
		<history>明朝</history>
		<description>九龙壁是原大圆镜智宝殿前的影壁，建于乾隆二十一年（1756年）。壁高5.96米，厚1.60米，长25.52米。壁的两面用七色琉璃砖瓦镶砌而成。两面各有九条彩色大蟠龙，飞腾戏珠于波涛云际之中。壁上共有大小蟠龙635条。中国现存三座古代九龙壁，唯独这座是双面壁，它是中国琉璃建筑艺术的精华。</description>
		<location>
			<x>213</x>
			<y>119</y>
		</location>
	</view_spot>
	<view_spot>
		<name>快雪堂</name>
		<history>清朝</history>
		<description>始建于乾隆四十四年（ 1775 年），院内还有澄观堂、浴兰轩两座大殿。四周由彩绘游廊连接，快雪堂东西两侧的游廊内嵌有晋代至元代二十位书法家八十篇墨迹石刻四十八方，其中王羲之快雪时晴帖与乾隆皇帝所做的快雪堂记最为著名。</description>
		<location>
			<x>187</x>
			<y>163</y>
		</location>
	</view_spot>
	<view_spot>
		<name>浴兰轩</name>
		<history>清朝</history>
		<description>清凉</description>
		<location>
			<x>185</x>
			<y>180</y>
		</location>
	</view_spot>
	<view_spot>
		<name>澄观堂</name>
		<history>清朝</history>
		<description>清凉</description>
		<location>
			<x>183</x>
			<y>195</y>
		</location>
	</view_spot>
	<view_spot>
		<name>滋香亭</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>183</x>
			<y>210</y>
		</location>
	</view_spot>
	<view_spot>
		<name>铁影壁</name>
		<history>元朝</history>
		<description>元代遗物，壁呈棕褐色，由中性火山块砾岩雕成，因颜色和质地似铁，故称铁影壁。壁高1.89米，长3.56米，两面浅雕云纹异兽，刻工古朴浑厚。铁影壁原是建德门（今德胜门）外一古庙前的照壁。明初，此壁被移到德胜门内护国德胜庵前（今铁影壁胡同内），1947年壁身移至北海公园。1986年北海公园从铁影壁胡同找回基座，从而使这一文物得以复原。</description>
		<location>
			<x>170</x>
			<y>210</y>
		</location>
	</view_spot>
	<view_spot>
		<name>宝积楼</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>152</x>
			<y>175</y>
		</location>
	</view_spot>
	<view_spot>
		<name>阐福寺</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>143</x>
			<y>202</y>
		</location>
	</view_spot>
	<view_spot>
		<name>五龙亭</name>
		<history>明朝</history>
		<description>建于明万历三十年（1602 年），中为龙泽亭，左为涌瑞亭、浮翠亭；右为澄祥亭、滋香亭。原是帝后及近臣垂钓赏月的地方，乾隆二十八年（ 1763 年）将木制弧形桥改为石桥，并安装了青石栏板、柱子。光绪二十六年（ 1900 年）栏板、柱子遭八国联军破坏， 1974年照原样予以恢复。现存五龙亭成为人们眺望白塔及北海湖光山色和休息的地方。</description>
		<location>
			<x>140</x>
			<y>223</y>
		</location>
	</view_spot>
	<view_spot>
		<name>澄祥亭</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>144</x>
			<y>231</y>
		</location>
	</view_spot>
	<view_spot>
		<name>龙泽亭</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>148</x>
			<y>239</y>
		</location>
	</view_spot>
	<view_spot>
		<name>小西天</name>
		<history>清朝</history>
		<description>小西天始建于清乾隆三十三年（公元1768 年），建成于清乾隆三十五年（公元1770 年），是清乾隆皇帝为母亲孝圣皇太后祝寿祈福而建的。主体建筑为极乐世界，总面积达1200平方米，其横梁跨度13.5米，是中国最大的方亭式宫殿建筑，殿四面窗扉、楠扇细镂花纹，殿内高处悬挂金匾，上书“极乐世界”为乾隆御笔。上方为金光灿灿的八角穹窿团龙藻井，十分庄严。殿四面环水，有桥可通，东西南北各有琉璃牌坊一座，四角各有一座小方亭，正南面有一道月牙河，上架一座雕栏石桥，整体建筑气势磅礴，雄伟壮观。殿内原有南海普陀泥塑一座，山上布有二百二十六尊罗汉佛像，山下绘满海水，以象征佛界普陀胜境，故有“罗汉山”和“海岛”之称</description>
		<location>
			<x>95</x>
			<y>225</y>
		</location>
	</view_spot>
	<view_spot>
		<name>万佛楼石碑</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>88</x>
			<y>262</y>
		</location>
	</view_spot>
	<view_spot>
		<name>西华艺楼</name>
		<history>明朝</history>
		<description>美丽</description>
		<location>
			<x>132</x>
			<y>537</y>
		</location>
	</view_spot>
	<view_spot>
		<name>团城</name>
		<history>元朝</history>
		<description>团城原是太液池中的一个小岛，金代为大宁宫一部分。元代称圆坻，亦称瀛洲。岛四周砌圆形城墙。城高4.6米，面积约4500平方米。周长276米。团城上殿宇堂皇别致，松柏苍劲挺拔。1961年国务院将团城列为全国重点文物保护单位。</description>
		<location>
			<x>284</x>
			<y>643</y>
		</location>
	</view_spot>
	<view_spot>
		<name>玉瓮</name>
		<history>元朝</history>
		<description>玉瓮又称“渎山大玉海”，制作于至元二年（1265年）。口呈椭圆形，通高70公分，周长493公分，重约3500公斤，周身浮雕海龙、海马、海猪、海犀等出没于波涛之中，栩栩如生。元世祖忽必烈曾将玉瓮放置琼华岛广寒殿中，传说曾用以盛酒大宴群臣。明代广寒殿倒塌，玉瓮失落民间。清乾隆十年（1745年）发现后，乾隆皇帝“令以千金易之，置承光殿中”，乾隆十四年（1749年）建玉瓮亭，将玉瓮陈设于亭中配以汉白玉雕花石座，命翰林四十人，各赋诗一首，刻于亭柱之上。玉瓮厚重古朴，气势雄浑。为元代难得的玉雕精品。</description>
		<location>
			<x>284</x>
			<y>652</y>
		</location>
	</view_spot>
	<view_spot>
		<name>先蚕坛</name>
		<history>清朝</history>
		<description>先蚕坛位于北海东北隅，总占地面积17000平方米。原为明代“雷霆洪应殿”旧址。清乾隆七年（1742年），建“先蚕坛”，成为后妃们祭祀“蚕神”的地方。院内建筑有“观桑台”、“亲蚕殿”、“后殿”、“先蚕神殿”、“神橱”、“蚕署”、“井亭”、“牲亭”、“蚕所”、“游廊”、“桑园”、“浴蚕池”等。东面有一条贯通南北的小河叫“浴蚕河”，是元代由金水河引入北海东边的一支水系。整体建筑宏伟，构造精美，绿瓦红墙，色彩艳丽。先蚕坛是北京九坛之一，是现存较完整的一处皇室祭祀场所。</description>
		<location>
			<x>406</x>
			<y>120</y>
		</location>
	</view_spot>
	<view_spot>
		<name>画舫斋</name>
		<history>清朝</history>
		<description>画舫斋位于北海东岸，建于清乾隆二十二年（1757年），是掩映在山林中的一处独立院落。前殿为“春雨淋塘”，中有水池，北为正殿“画舫斋”。东西各有一处精巧别致的院落，东为“古柯庭”，西为“小玲珑”。整个画舫斋朱廊环绕，结构精巧，环境别致，形似停泊在北海湖边的一条大船，原引用欧阳修的《画舫斋记》而造其形，得其名。乾隆皇帝经常到此游玩，光绪皇帝曾在此居住，慈禧太后也常来这里游宴、听评书。</description>
		<location>
			<x>411</x>
			<y>197</y>
		</location>
	</view_spot>
	<view_spot>
		<name>古籁堂</name>
		<history>元朝</history>
		<description>清凉</description>
		<location>
			<x>289</x>
			<y>632</y>
		</location>
	</view_spot>
	<view_spot>
		<name>积翠</name>
		<history>元朝</history>
		<description>建于十三世纪，是连接团城和琼岛的纽带。桥用汉白玉石砌成。</description>
		<location>
			<x>281</x>
			<y>613</y>
		</location>
	</view_spot>
	<view_spot>
		<name>堆云</name>
		<history>元朝</history>
		<description>建于十三世纪，是连接团城和琼岛的纽带。桥用汉白玉石砌成。</description>
		<location>
			<x>292</x>
			<y>569</y>
		</location>
	</view_spot>
	<view_spot>
		<name>文创堂</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>323</x>
			<y>561</y>
		</location>
	</view_spot>
	<view_spot>
		<name>漪莲轩</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>382</x>
			<y>596</y>
		</location>
	</view_spot>
	<view_spot>
		<name>钟楼</name>
		<history>明朝</history>
		<description>庄严</description>
		<location>
			<x>296</x>
			<y>540</y>
		</location>
	</view_spot>
	<view_spot>
		<name>悦心殿</name>
		<history>清朝</history>
		<description>清凉</description>
		<location>
			<x>260</x>
			<y>510</y>
		</location>
	</view_spot>
	<view_spot>
		<name>涤蔼亭</name>
		<history>清朝</history>
		<description>清凉</description>
		<location>
			<x>284</x>
			<y>521</y>
		</location>
	</view_spot>
	<view_spot>
		<name>引胜亭</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>296</x>
			<y>519</y>
		</location>
	</view_spot>
	<view_spot>
		<name>慧日亭</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>321</x>
			<y>500</y>
		</location>
	</view_spot>
	<view_spot>
		<name>琼华岛</name>
		<history>清朝</history>
		<description>琼华岛简称琼岛，因岛上建有白塔，故又俗称"白塔山"。岛高32.米，周长913米。琼华，意指华丽的美玉，以此命名，表示该岛是用美玉建成的仙境宝岛。另据神话传说，琼华是琼树之花（华即花），生长在蓬莱仙岛上，人吃了可长生不老，此亦表示该岛是仿瑶池仙境建筑的。清初，曾在山顶设置信炮台，由八旗军驻守，居高临下，*'望全城，一旦有警，便可立即发出信号。</description>
		<location>
			<x>284</x>
			<y>485</y>
		</location>
	</view_spot>
	<view_spot>
		<name>撷秀亭</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>232</x>
			<y>463</y>
		</location>
	</view_spot>
	<view_spot>
		<name>琳光殿</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>228</x>
			<y>477</y>
		</location>
	</view_spot>
	<view_spot>
		<name>阅古楼</name>
		<history>清朝</history>
		<description>阅古楼平面近似椭圆形，实为两个半圆左右围合而成的上下两层楼，楼形别具一格。楼内沿墙壁镶嵌着由梁诗正等奉命编次的魏晋以来历代名墨迹的钩摹石刻，共495方，清代帝后常来此阅赏古代翰墨。楼内四壁嵌满《三希堂法帖》石刻，这些是中国古代书法集成的石刻珍品。</description>
		<location>
			<x>244</x>
			<y>445</y>
		</location>
	</view_spot>
	<view_spot>
		<name>分凉阁</name>
		<history>清朝</history>
		<description>清凉</description>
		<location>
			<x>261</x>
			<y>426</y>
		</location>
	</view_spot>
	<view_spot>
		<name>长廊</name>
		<history>清朝</history>
		<description>清凉</description>
		<location>
			<x>285</x>
			<y>409</y>
		</location>
	</view_spot>
	<view_spot>
		<name>琼华古洞</name>
		<history>清朝</history>
		<description>清凉</description>
		<location>
			<x>290</x>
			<y>431</y>
		</location>
	</view_spot>
	<view_spot>
		<name>见春亭</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>323</x>
			<y>455</y>
		</location>
	</view_spot>
	<view_spot>
		<name>古遗堂</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>312</x>
			<y>450</y>
		</location>
	</view_spot>
	<view_spot>
		<name>倚晴楼</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>321</x>
			<y>427</y>
		</location>
	</view_spot>
	<view_spot>
		<name>船坞</name>
		<history>明朝</history>
		<description>清凉</description>
		<location>
			<x>409</x>
			<y>253</y>
		</location>
	</view_spot>
	<view_spot>
		<name>濠濮间</name>
		<history>清朝</history>
		<description>濠濮间是北海公园的一处园中之园。“濠”与“濮”均为中国古水名。据《庄子.秋水》载，庄子与惠施游于濠梁之上，庄子说：“鱼儿出来了，鱼儿真快乐。”惠施问：“你不是鱼，怎么知鱼之乐？”庄子反驳说：“你不是我，怎知我不知鱼之乐？”据此人们修此小园，园内小桥几近水面，以供帝后观鱼、垂钓。乾隆皇帝曾在此园宴请大臣。</description>
		<location>
			<x>445</x>
			<y>279</y>
		</location>
	</view_spot>
</park>
